[project]
name = "lead_qualification"
version = "0.1.0"
description = "lead_qualification using crewAI"
authors = [{ name = "Priyanka Gangwar", email = "priyankagangwar121097@gmail.com" }]
requires-python = ">=3.12,<3.14"

dependencies = [
    "crewai[tools]==1.15.2",
    "litellm==1.74.15",
    "streamlit",
    "pandas"
]

[project.scripts]
lead_qualification = "lead_qualification.main:run"
run_crew = "lead_qualification.main:run"
train = "lead_qualification.main:train"
replay = "lead_qualification.main:replay"
test = "lead_qualification.main:test"
run_with_trigger = "lead_qualification.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"